@startuml ER

skinparam class {
  backgroundColor white
  backgroundColor<<sense>> #e8f5fc
  backgroundColor<<sense_frame>> #f9ecf9
  backgroundColor<<lexical_unit>> #f9ffe6
  backgroundColor<<syntactic_structure>> #f9f2ec
  backgroundColor<<morphological>> #e6ffe6
  backgroundColor<<example>> #ffffe6
  backgroundColor<<feature>> #f2f2f2
  backgroundColor<<multilingual>> #ffe6e6
  backgroundColor<<connections>> #fff0e6
  borderColor black
  borderColor<<sense>> #5FB8EC
  borderColor<<sense_frame>> #d477d4
  borderColor<<lexical_unit>> #9ccc00
  borderColor<<syntactic_structure>> #996633
  borderColor<<morphological>> #00b300
  borderColor<<example>> #cccc00
  borderColor<<feature>> #737373
  borderColor<<multilingual>> #b30000
  borderColor<<connections>> #e65c00
  arrowColor black
}

skinparam rectangle {
  backgroundColor white
  borderColor<<sense>> #5FB8EC
  borderColor<<sense_frame>> #d477d4
  borderColor<<lexical_unit>> #9ccc00
  borderColor<<syntactic_structure>> #996633
  borderColor<<morphological>> #00b300
  borderColor<<example>> #cccc00
  borderColor<<feature>> #737373
  borderColor<<multilingual>> #b30000
  borderColor<<connections>> #e65c00
}

skinparam backgroundcolor transparent
'left to right direction
hide circle
hide stereotype
'hide members

rectangle "<color:#737373>generic features" <<feature>> {

  entity "<U+0020>**measure** " as measure <<feature>> {
    id: INT <<PK>>
    --
    name: VARCHAR(45)
  }

  entity "<U+0020>**feature_category** " as feature_category <<feature>> {
    id: INT <<PK>>
    --
    name: VARCHAR(45)
  }

  entity "<U+0020>**feature** " as feature <<feature>> {
    id: INT <<PK>>
    <color:#gray>category_id: INT <<FK>>
    --
    name: VARCHAR(45)
  }

  entity "<U+0020>**feature_value** " as feature_value <<feature>> {
    id: INT <<PK>>
    <color:#gray>feature_id: INT <<FK>>
    --
    value: VARCHAR(45)
  }

  entity "<U+0020>**feature_value_relation_type** " as feature_value_relation_type <<feature>> {
    id: INT <<PK>>
    --
    name: VARCHAR(45)
  }

  entity "<U+0020>**feature_value_relation** " as feature_value_relation <<feature>> {
    <color:red>id: INT <<PK>>
    <color:#gray>from_value_id: INT <<FK>>
    <color:#gray>to_value_id: INT <<FK>>
    <color:#gray>type_id: INT <<FK>>
  }

  feature }|-left-|| feature_category

  feature_value }|--|| feature

  feature_value_relation }|--|| feature_value_relation_type
  feature_value_relation }|--|| feature_value
  feature_value_relation }|--|| feature_value

}

entity "<U+0020>**object_feature** " as object_feature {
  id: INT <<PK>>
  <color:#gray>value_id: INT <<FK>>
  --
  object_id: INT
  content_type_id: INT
}

entity "<U+0020>**sense_measure** " as sense_measure <<sense>> {
  id: INT <<PK>>
  <color:#gray>sense_id: INT <<FK>>
  <color:#gray>corpus_id: INT <<FK>>
  <color:#gray>measure_id: INT <<FK>>
  --
  value: FLOAT
}

entity "<U+0020>**form_representation_measure** " as form_representation_measure <<morphological>> {
  id: INT <<PK>>
  <color:#gray>form_representation_id: INT <<FK>>
  <color:#gray>corpus_id: INT <<FK>>
  <color:#gray>measure_id: INT <<FK>>
  --
  value: FLOAT
}

object_feature }|..|| feature_value

sense_measure }|..|| measure

form_representation_measure }|..|| measure

@enduml