@startuml ER

skinparam class {
  backgroundColor white
  backgroundColor<<sense>> #e8f5fc
  backgroundColor<<sense_frame>> #f9ecf9
  backgroundColor<<lexical_unit>> #f9ffe6
  backgroundColor<<syntactic_structure>> #f9f2ec
  backgroundColor<<morphological>> #e6ffe6
  backgroundColor<<example>> #ffffe6
  backgroundColor<<feature>> #f2f2f2
  backgroundColor<<multilingual>> #ffe6e6
  backgroundColor<<connections>> #fff0e6
  borderColor black
  borderColor<<sense>> #5FB8EC
  borderColor<<sense_frame>> #d477d4
  borderColor<<lexical_unit>> #9ccc00
  borderColor<<syntactic_structure>> #996633
  borderColor<<morphological>> #00b300
  borderColor<<example>> #cccc00
  borderColor<<feature>> #737373
  borderColor<<multilingual>> #b30000
  borderColor<<connections>> #e65c00
  arrowColor black
}

skinparam rectangle {
  backgroundColor white
  borderColor<<sense>> #5FB8EC
  borderColor<<sense_frame>> #d477d4
  borderColor<<lexical_unit>> #9ccc00
  borderColor<<syntactic_structure>> #996633
  borderColor<<morphological>> #00b300
  borderColor<<example>> #cccc00
  borderColor<<feature>> #737373
  borderColor<<multilingual>> #b30000
  borderColor<<connections>> #e65c00
}

skinparam backgroundcolor transparent
'left to right direction
hide circle
hide stereotype
'hide members

rectangle "<color:#e65c00>resource connections" <<connections>> {
  entity "**status**" as status <<connections>> {
    id: INT <<PK>>
    --
    name: VARCHAR(45)
  }

  entity "**resource**" as resource <<connections>> {
    id: INT <<PK>>
    --
    name: VARCHAR(45)
  }

  entity "**resource_status**" as resource_status <<connections>> {
    <color:red>id: INT <<PK>>
    <color:#gray>resource_id: INT <<FK>>
    <color:#gray>status_id: INT <<FK>>
  }

  entity "<U+0020>**resource_language** " as resource_language <<connections>> {
    <color:red>id: INT <<PK>>
    <color:#gray>resource_id: INT <<FK>>
    <color:#gray>language_id: INT <<FK>>
  }

  entity "<U+0020>**resource_relevance_inclusion** " as resource_relevance_inclusion <<connections>> {
    id: INT <<PK>>
    name: VARCHAR(45)
  }

  entity "**resource_relevance_status**" as resource_relevance_status <<connections>> {
    id: INT <<PK>>
    name: VARCHAR(45)
  }

  entity "**lexical_unit_status**" as lexical_unit_status <<connections>> {
    <color:red>id: INT <<PK>>
    <color:#gray>lexical_unit_id: INT <<FK>>
    <color:#gray>resource_status_id: INT <<FK>>
  }

  resource_status }|-left-|| status
  resource_status }|-down-|| resource
  
  resource_language }|-right-|| resource
  lexical_unit_status }|--|| resource_status
  
}

entity "**language**" as language <<multilingual>> {
  id: INT <<PK>>
  --
  name: VARCHAR(45)
}

entity "<U+0020>**resource_relevance** " as resource_relevance {
  id: INT <<PK>>
  <color:#gray>resource_id: INT <<FK>>
  <color:#gray>headword_id: INT <<FK>>
  <color:#gray>inclusion_id: INT
  <color:#gray>status_id: INT
  --
  object_id: INT
  content_type_id: INT
}

entity "<U+0020>**lexical_unit** " as lexical_unit <<lexical_unit>> {
  id: INT <<PK>>
  <color:#gray>syntactic_structure_id: INT <<FK>>
  <color:#gray>type_id: INT <<FK>>
}

resource_language }|.down.|| language
lexical_unit_status }|.up.|| lexical_unit

resource_relevance }|.up.|| resource_relevance_inclusion
resource_relevance }|.up.|| resource_relevance_status
resource_relevance }|.left.|| resource

@enduml